// Code generated by mockery v2.52.1. DO NOT EDIT.

package oscar

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	state "github.com/mk6i/retro-aim-server/state"

	wire "github.com/mk6i/retro-aim-server/wire"
)

// mockHandlerFunc is an autogenerated mock type for the HandlerFunc type
type mockHandlerFunc struct {
	mock.Mock
}

type mockHandlerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHandlerFunc) EXPECT() *mockHandlerFunc_Expecter {
	return &mockHandlerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, sess, inFrame, r, rw
func (_m *mockHandlerFunc) Execute(ctx context.Context, sess *state.Session, inFrame wire.SNACFrame, r io.Reader, rw ResponseWriter) error {
	ret := _m.Called(ctx, sess, inFrame, r, rw)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, wire.SNACFrame, io.Reader, ResponseWriter) error); ok {
		r0 = rf(ctx, sess, inFrame, r, rw)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockHandlerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockHandlerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - inFrame wire.SNACFrame
//   - r io.Reader
//   - rw ResponseWriter
func (_e *mockHandlerFunc_Expecter) Execute(ctx interface{}, sess interface{}, inFrame interface{}, r interface{}, rw interface{}) *mockHandlerFunc_Execute_Call {
	return &mockHandlerFunc_Execute_Call{Call: _e.mock.On("Execute", ctx, sess, inFrame, r, rw)}
}

func (_c *mockHandlerFunc_Execute_Call) Run(run func(ctx context.Context, sess *state.Session, inFrame wire.SNACFrame, r io.Reader, rw ResponseWriter)) *mockHandlerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*state.Session), args[2].(wire.SNACFrame), args[3].(io.Reader), args[4].(ResponseWriter))
	})
	return _c
}

func (_c *mockHandlerFunc_Execute_Call) Return(_a0 error) *mockHandlerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockHandlerFunc_Execute_Call) RunAndReturn(run func(context.Context, *state.Session, wire.SNACFrame, io.Reader, ResponseWriter) error) *mockHandlerFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockHandlerFunc creates a new instance of mockHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockHandlerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockHandlerFunc {
	mock := &mockHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
