// Code generated by mockery v2.38.0. DO NOT EDIT.

package server

import (
	context "context"

	oscar "github.com/mk6i/retro-aim-server/oscar"
	mock "github.com/stretchr/testify/mock"

	state "github.com/mk6i/retro-aim-server/state"
)

// mockICBMHandler is an autogenerated mock type for the ICBMHandler type
type mockICBMHandler struct {
	mock.Mock
}

type mockICBMHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockICBMHandler) EXPECT() *mockICBMHandler_Expecter {
	return &mockICBMHandler_Expecter{mock: &_m.Mock}
}

// ChannelMsgToHostHandler provides a mock function with given fields: ctx, sess, inFrame, inBody
func (_m *mockICBMHandler) ChannelMsgToHostHandler(ctx context.Context, sess *state.Session, inFrame oscar.SNACFrame, inBody oscar.SNAC_0x04_0x06_ICBMChannelMsgToHost) (*oscar.SNACMessage, error) {
	ret := _m.Called(ctx, sess, inFrame, inBody)

	if len(ret) == 0 {
		panic("no return value specified for ChannelMsgToHostHandler")
	}

	var r0 *oscar.SNACMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x04_0x06_ICBMChannelMsgToHost) (*oscar.SNACMessage, error)); ok {
		return rf(ctx, sess, inFrame, inBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x04_0x06_ICBMChannelMsgToHost) *oscar.SNACMessage); ok {
		r0 = rf(ctx, sess, inFrame, inBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oscar.SNACMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x04_0x06_ICBMChannelMsgToHost) error); ok {
		r1 = rf(ctx, sess, inFrame, inBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockICBMHandler_ChannelMsgToHostHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChannelMsgToHostHandler'
type mockICBMHandler_ChannelMsgToHostHandler_Call struct {
	*mock.Call
}

// ChannelMsgToHostHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - inFrame oscar.SNACFrame
//   - inBody oscar.SNAC_0x04_0x06_ICBMChannelMsgToHost
func (_e *mockICBMHandler_Expecter) ChannelMsgToHostHandler(ctx interface{}, sess interface{}, inFrame interface{}, inBody interface{}) *mockICBMHandler_ChannelMsgToHostHandler_Call {
	return &mockICBMHandler_ChannelMsgToHostHandler_Call{Call: _e.mock.On("ChannelMsgToHostHandler", ctx, sess, inFrame, inBody)}
}

func (_c *mockICBMHandler_ChannelMsgToHostHandler_Call) Run(run func(ctx context.Context, sess *state.Session, inFrame oscar.SNACFrame, inBody oscar.SNAC_0x04_0x06_ICBMChannelMsgToHost)) *mockICBMHandler_ChannelMsgToHostHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*state.Session), args[2].(oscar.SNACFrame), args[3].(oscar.SNAC_0x04_0x06_ICBMChannelMsgToHost))
	})
	return _c
}

func (_c *mockICBMHandler_ChannelMsgToHostHandler_Call) Return(_a0 *oscar.SNACMessage, _a1 error) *mockICBMHandler_ChannelMsgToHostHandler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockICBMHandler_ChannelMsgToHostHandler_Call) RunAndReturn(run func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x04_0x06_ICBMChannelMsgToHost) (*oscar.SNACMessage, error)) *mockICBMHandler_ChannelMsgToHostHandler_Call {
	_c.Call.Return(run)
	return _c
}

// ClientEventHandler provides a mock function with given fields: ctx, sess, inFrame, inBody
func (_m *mockICBMHandler) ClientEventHandler(ctx context.Context, sess *state.Session, inFrame oscar.SNACFrame, inBody oscar.SNAC_0x04_0x14_ICBMClientEvent) error {
	ret := _m.Called(ctx, sess, inFrame, inBody)

	if len(ret) == 0 {
		panic("no return value specified for ClientEventHandler")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x04_0x14_ICBMClientEvent) error); ok {
		r0 = rf(ctx, sess, inFrame, inBody)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockICBMHandler_ClientEventHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientEventHandler'
type mockICBMHandler_ClientEventHandler_Call struct {
	*mock.Call
}

// ClientEventHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - inFrame oscar.SNACFrame
//   - inBody oscar.SNAC_0x04_0x14_ICBMClientEvent
func (_e *mockICBMHandler_Expecter) ClientEventHandler(ctx interface{}, sess interface{}, inFrame interface{}, inBody interface{}) *mockICBMHandler_ClientEventHandler_Call {
	return &mockICBMHandler_ClientEventHandler_Call{Call: _e.mock.On("ClientEventHandler", ctx, sess, inFrame, inBody)}
}

func (_c *mockICBMHandler_ClientEventHandler_Call) Run(run func(ctx context.Context, sess *state.Session, inFrame oscar.SNACFrame, inBody oscar.SNAC_0x04_0x14_ICBMClientEvent)) *mockICBMHandler_ClientEventHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*state.Session), args[2].(oscar.SNACFrame), args[3].(oscar.SNAC_0x04_0x14_ICBMClientEvent))
	})
	return _c
}

func (_c *mockICBMHandler_ClientEventHandler_Call) Return(_a0 error) *mockICBMHandler_ClientEventHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockICBMHandler_ClientEventHandler_Call) RunAndReturn(run func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x04_0x14_ICBMClientEvent) error) *mockICBMHandler_ClientEventHandler_Call {
	_c.Call.Return(run)
	return _c
}

// EvilRequestHandler provides a mock function with given fields: ctx, sess, inFrame, inBody
func (_m *mockICBMHandler) EvilRequestHandler(ctx context.Context, sess *state.Session, inFrame oscar.SNACFrame, inBody oscar.SNAC_0x04_0x08_ICBMEvilRequest) (oscar.SNACMessage, error) {
	ret := _m.Called(ctx, sess, inFrame, inBody)

	if len(ret) == 0 {
		panic("no return value specified for EvilRequestHandler")
	}

	var r0 oscar.SNACMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x04_0x08_ICBMEvilRequest) (oscar.SNACMessage, error)); ok {
		return rf(ctx, sess, inFrame, inBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x04_0x08_ICBMEvilRequest) oscar.SNACMessage); ok {
		r0 = rf(ctx, sess, inFrame, inBody)
	} else {
		r0 = ret.Get(0).(oscar.SNACMessage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x04_0x08_ICBMEvilRequest) error); ok {
		r1 = rf(ctx, sess, inFrame, inBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockICBMHandler_EvilRequestHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvilRequestHandler'
type mockICBMHandler_EvilRequestHandler_Call struct {
	*mock.Call
}

// EvilRequestHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - inFrame oscar.SNACFrame
//   - inBody oscar.SNAC_0x04_0x08_ICBMEvilRequest
func (_e *mockICBMHandler_Expecter) EvilRequestHandler(ctx interface{}, sess interface{}, inFrame interface{}, inBody interface{}) *mockICBMHandler_EvilRequestHandler_Call {
	return &mockICBMHandler_EvilRequestHandler_Call{Call: _e.mock.On("EvilRequestHandler", ctx, sess, inFrame, inBody)}
}

func (_c *mockICBMHandler_EvilRequestHandler_Call) Run(run func(ctx context.Context, sess *state.Session, inFrame oscar.SNACFrame, inBody oscar.SNAC_0x04_0x08_ICBMEvilRequest)) *mockICBMHandler_EvilRequestHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*state.Session), args[2].(oscar.SNACFrame), args[3].(oscar.SNAC_0x04_0x08_ICBMEvilRequest))
	})
	return _c
}

func (_c *mockICBMHandler_EvilRequestHandler_Call) Return(_a0 oscar.SNACMessage, _a1 error) *mockICBMHandler_EvilRequestHandler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockICBMHandler_EvilRequestHandler_Call) RunAndReturn(run func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x04_0x08_ICBMEvilRequest) (oscar.SNACMessage, error)) *mockICBMHandler_EvilRequestHandler_Call {
	_c.Call.Return(run)
	return _c
}

// ParameterQueryHandler provides a mock function with given fields: ctx, inFrame
func (_m *mockICBMHandler) ParameterQueryHandler(ctx context.Context, inFrame oscar.SNACFrame) oscar.SNACMessage {
	ret := _m.Called(ctx, inFrame)

	if len(ret) == 0 {
		panic("no return value specified for ParameterQueryHandler")
	}

	var r0 oscar.SNACMessage
	if rf, ok := ret.Get(0).(func(context.Context, oscar.SNACFrame) oscar.SNACMessage); ok {
		r0 = rf(ctx, inFrame)
	} else {
		r0 = ret.Get(0).(oscar.SNACMessage)
	}

	return r0
}

// mockICBMHandler_ParameterQueryHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParameterQueryHandler'
type mockICBMHandler_ParameterQueryHandler_Call struct {
	*mock.Call
}

// ParameterQueryHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - inFrame oscar.SNACFrame
func (_e *mockICBMHandler_Expecter) ParameterQueryHandler(ctx interface{}, inFrame interface{}) *mockICBMHandler_ParameterQueryHandler_Call {
	return &mockICBMHandler_ParameterQueryHandler_Call{Call: _e.mock.On("ParameterQueryHandler", ctx, inFrame)}
}

func (_c *mockICBMHandler_ParameterQueryHandler_Call) Run(run func(ctx context.Context, inFrame oscar.SNACFrame)) *mockICBMHandler_ParameterQueryHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oscar.SNACFrame))
	})
	return _c
}

func (_c *mockICBMHandler_ParameterQueryHandler_Call) Return(_a0 oscar.SNACMessage) *mockICBMHandler_ParameterQueryHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockICBMHandler_ParameterQueryHandler_Call) RunAndReturn(run func(context.Context, oscar.SNACFrame) oscar.SNACMessage) *mockICBMHandler_ParameterQueryHandler_Call {
	_c.Call.Return(run)
	return _c
}

// newMockICBMHandler creates a new instance of mockICBMHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockICBMHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockICBMHandler {
	mock := &mockICBMHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
