// Code generated by mockery v2.34.2. DO NOT EDIT.

package server

import (
	context "context"

	oscar "github.com/mkaminski/goaim/oscar"
	mock "github.com/stretchr/testify/mock"

	state "github.com/mkaminski/goaim/state"
)

// mockLocateHandler is an autogenerated mock type for the LocateHandler type
type mockLocateHandler struct {
	mock.Mock
}

type mockLocateHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockLocateHandler) EXPECT() *mockLocateHandler_Expecter {
	return &mockLocateHandler_Expecter{mock: &_m.Mock}
}

// RightsQueryHandler provides a mock function with given fields: ctx
func (_m *mockLocateHandler) RightsQueryHandler(ctx context.Context) oscar.XMessage {
	ret := _m.Called(ctx)

	var r0 oscar.XMessage
	if rf, ok := ret.Get(0).(func(context.Context) oscar.XMessage); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(oscar.XMessage)
	}

	return r0
}

// mockLocateHandler_RightsQueryHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RightsQueryHandler'
type mockLocateHandler_RightsQueryHandler_Call struct {
	*mock.Call
}

// RightsQueryHandler is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockLocateHandler_Expecter) RightsQueryHandler(ctx interface{}) *mockLocateHandler_RightsQueryHandler_Call {
	return &mockLocateHandler_RightsQueryHandler_Call{Call: _e.mock.On("RightsQueryHandler", ctx)}
}

func (_c *mockLocateHandler_RightsQueryHandler_Call) Run(run func(ctx context.Context)) *mockLocateHandler_RightsQueryHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockLocateHandler_RightsQueryHandler_Call) Return(_a0 oscar.XMessage) *mockLocateHandler_RightsQueryHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockLocateHandler_RightsQueryHandler_Call) RunAndReturn(run func(context.Context) oscar.XMessage) *mockLocateHandler_RightsQueryHandler_Call {
	_c.Call.Return(run)
	return _c
}

// SetDirInfoHandler provides a mock function with given fields: ctx
func (_m *mockLocateHandler) SetDirInfoHandler(ctx context.Context) oscar.XMessage {
	ret := _m.Called(ctx)

	var r0 oscar.XMessage
	if rf, ok := ret.Get(0).(func(context.Context) oscar.XMessage); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(oscar.XMessage)
	}

	return r0
}

// mockLocateHandler_SetDirInfoHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDirInfoHandler'
type mockLocateHandler_SetDirInfoHandler_Call struct {
	*mock.Call
}

// SetDirInfoHandler is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockLocateHandler_Expecter) SetDirInfoHandler(ctx interface{}) *mockLocateHandler_SetDirInfoHandler_Call {
	return &mockLocateHandler_SetDirInfoHandler_Call{Call: _e.mock.On("SetDirInfoHandler", ctx)}
}

func (_c *mockLocateHandler_SetDirInfoHandler_Call) Run(run func(ctx context.Context)) *mockLocateHandler_SetDirInfoHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockLocateHandler_SetDirInfoHandler_Call) Return(_a0 oscar.XMessage) *mockLocateHandler_SetDirInfoHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockLocateHandler_SetDirInfoHandler_Call) RunAndReturn(run func(context.Context) oscar.XMessage) *mockLocateHandler_SetDirInfoHandler_Call {
	_c.Call.Return(run)
	return _c
}

// SetInfoHandler provides a mock function with given fields: ctx, sess, snacPayloadIn
func (_m *mockLocateHandler) SetInfoHandler(ctx context.Context, sess *state.Session, snacPayloadIn oscar.SNAC_0x02_0x04_LocateSetInfo) error {
	ret := _m.Called(ctx, sess, snacPayloadIn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, oscar.SNAC_0x02_0x04_LocateSetInfo) error); ok {
		r0 = rf(ctx, sess, snacPayloadIn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockLocateHandler_SetInfoHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetInfoHandler'
type mockLocateHandler_SetInfoHandler_Call struct {
	*mock.Call
}

// SetInfoHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - snacPayloadIn oscar.SNAC_0x02_0x04_LocateSetInfo
func (_e *mockLocateHandler_Expecter) SetInfoHandler(ctx interface{}, sess interface{}, snacPayloadIn interface{}) *mockLocateHandler_SetInfoHandler_Call {
	return &mockLocateHandler_SetInfoHandler_Call{Call: _e.mock.On("SetInfoHandler", ctx, sess, snacPayloadIn)}
}

func (_c *mockLocateHandler_SetInfoHandler_Call) Run(run func(ctx context.Context, sess *state.Session, snacPayloadIn oscar.SNAC_0x02_0x04_LocateSetInfo)) *mockLocateHandler_SetInfoHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*state.Session), args[2].(oscar.SNAC_0x02_0x04_LocateSetInfo))
	})
	return _c
}

func (_c *mockLocateHandler_SetInfoHandler_Call) Return(_a0 error) *mockLocateHandler_SetInfoHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockLocateHandler_SetInfoHandler_Call) RunAndReturn(run func(context.Context, *state.Session, oscar.SNAC_0x02_0x04_LocateSetInfo) error) *mockLocateHandler_SetInfoHandler_Call {
	_c.Call.Return(run)
	return _c
}

// SetKeywordInfoHandler provides a mock function with given fields: ctx
func (_m *mockLocateHandler) SetKeywordInfoHandler(ctx context.Context) oscar.XMessage {
	ret := _m.Called(ctx)

	var r0 oscar.XMessage
	if rf, ok := ret.Get(0).(func(context.Context) oscar.XMessage); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(oscar.XMessage)
	}

	return r0
}

// mockLocateHandler_SetKeywordInfoHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetKeywordInfoHandler'
type mockLocateHandler_SetKeywordInfoHandler_Call struct {
	*mock.Call
}

// SetKeywordInfoHandler is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockLocateHandler_Expecter) SetKeywordInfoHandler(ctx interface{}) *mockLocateHandler_SetKeywordInfoHandler_Call {
	return &mockLocateHandler_SetKeywordInfoHandler_Call{Call: _e.mock.On("SetKeywordInfoHandler", ctx)}
}

func (_c *mockLocateHandler_SetKeywordInfoHandler_Call) Run(run func(ctx context.Context)) *mockLocateHandler_SetKeywordInfoHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockLocateHandler_SetKeywordInfoHandler_Call) Return(_a0 oscar.XMessage) *mockLocateHandler_SetKeywordInfoHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockLocateHandler_SetKeywordInfoHandler_Call) RunAndReturn(run func(context.Context) oscar.XMessage) *mockLocateHandler_SetKeywordInfoHandler_Call {
	_c.Call.Return(run)
	return _c
}

// UserInfoQuery2Handler provides a mock function with given fields: ctx, sess, snacPayloadIn
func (_m *mockLocateHandler) UserInfoQuery2Handler(ctx context.Context, sess *state.Session, snacPayloadIn oscar.SNAC_0x02_0x15_LocateUserInfoQuery2) (oscar.XMessage, error) {
	ret := _m.Called(ctx, sess, snacPayloadIn)

	var r0 oscar.XMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, oscar.SNAC_0x02_0x15_LocateUserInfoQuery2) (oscar.XMessage, error)); ok {
		return rf(ctx, sess, snacPayloadIn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, oscar.SNAC_0x02_0x15_LocateUserInfoQuery2) oscar.XMessage); ok {
		r0 = rf(ctx, sess, snacPayloadIn)
	} else {
		r0 = ret.Get(0).(oscar.XMessage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *state.Session, oscar.SNAC_0x02_0x15_LocateUserInfoQuery2) error); ok {
		r1 = rf(ctx, sess, snacPayloadIn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockLocateHandler_UserInfoQuery2Handler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserInfoQuery2Handler'
type mockLocateHandler_UserInfoQuery2Handler_Call struct {
	*mock.Call
}

// UserInfoQuery2Handler is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - snacPayloadIn oscar.SNAC_0x02_0x15_LocateUserInfoQuery2
func (_e *mockLocateHandler_Expecter) UserInfoQuery2Handler(ctx interface{}, sess interface{}, snacPayloadIn interface{}) *mockLocateHandler_UserInfoQuery2Handler_Call {
	return &mockLocateHandler_UserInfoQuery2Handler_Call{Call: _e.mock.On("UserInfoQuery2Handler", ctx, sess, snacPayloadIn)}
}

func (_c *mockLocateHandler_UserInfoQuery2Handler_Call) Run(run func(ctx context.Context, sess *state.Session, snacPayloadIn oscar.SNAC_0x02_0x15_LocateUserInfoQuery2)) *mockLocateHandler_UserInfoQuery2Handler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*state.Session), args[2].(oscar.SNAC_0x02_0x15_LocateUserInfoQuery2))
	})
	return _c
}

func (_c *mockLocateHandler_UserInfoQuery2Handler_Call) Return(_a0 oscar.XMessage, _a1 error) *mockLocateHandler_UserInfoQuery2Handler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockLocateHandler_UserInfoQuery2Handler_Call) RunAndReturn(run func(context.Context, *state.Session, oscar.SNAC_0x02_0x15_LocateUserInfoQuery2) (oscar.XMessage, error)) *mockLocateHandler_UserInfoQuery2Handler_Call {
	_c.Call.Return(run)
	return _c
}

// newMockLocateHandler creates a new instance of mockLocateHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLocateHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLocateHandler {
	mock := &mockLocateHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
