// Code generated by mockery v2.35.2. DO NOT EDIT.

package server

import (
	oscar "github.com/mkaminski/goaim/oscar"
	mock "github.com/stretchr/testify/mock"
)

// MockChatNavHandler is an autogenerated mock type for the ChatNavHandler type
type MockChatNavHandler struct {
	mock.Mock
}

type MockChatNavHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatNavHandler) EXPECT() *MockChatNavHandler_Expecter {
	return &MockChatNavHandler_Expecter{mock: &_m.Mock}
}

// CreateRoomHandler provides a mock function with given fields: sess, cr, newChatRoom, snacPayloadIn
func (_m *MockChatNavHandler) CreateRoomHandler(sess *Session, cr *ChatRegistry, newChatRoom ChatRoomFactory, snacPayloadIn oscar.SNAC_0x0E_0x02_ChatRoomInfoUpdate) (XMessage, error) {
	ret := _m.Called(sess, cr, newChatRoom, snacPayloadIn)

	var r0 XMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(*Session, *ChatRegistry, ChatRoomFactory, oscar.SNAC_0x0E_0x02_ChatRoomInfoUpdate) (XMessage, error)); ok {
		return rf(sess, cr, newChatRoom, snacPayloadIn)
	}
	if rf, ok := ret.Get(0).(func(*Session, *ChatRegistry, ChatRoomFactory, oscar.SNAC_0x0E_0x02_ChatRoomInfoUpdate) XMessage); ok {
		r0 = rf(sess, cr, newChatRoom, snacPayloadIn)
	} else {
		r0 = ret.Get(0).(XMessage)
	}

	if rf, ok := ret.Get(1).(func(*Session, *ChatRegistry, ChatRoomFactory, oscar.SNAC_0x0E_0x02_ChatRoomInfoUpdate) error); ok {
		r1 = rf(sess, cr, newChatRoom, snacPayloadIn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatNavHandler_CreateRoomHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoomHandler'
type MockChatNavHandler_CreateRoomHandler_Call struct {
	*mock.Call
}

// CreateRoomHandler is a helper method to define mock.On call
//   - sess *Session
//   - cr *ChatRegistry
//   - newChatRoom ChatRoomFactory
//   - snacPayloadIn oscar.SNAC_0x0E_0x02_ChatRoomInfoUpdate
func (_e *MockChatNavHandler_Expecter) CreateRoomHandler(sess interface{}, cr interface{}, newChatRoom interface{}, snacPayloadIn interface{}) *MockChatNavHandler_CreateRoomHandler_Call {
	return &MockChatNavHandler_CreateRoomHandler_Call{Call: _e.mock.On("CreateRoomHandler", sess, cr, newChatRoom, snacPayloadIn)}
}

func (_c *MockChatNavHandler_CreateRoomHandler_Call) Run(run func(sess *Session, cr *ChatRegistry, newChatRoom ChatRoomFactory, snacPayloadIn oscar.SNAC_0x0E_0x02_ChatRoomInfoUpdate)) *MockChatNavHandler_CreateRoomHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Session), args[1].(*ChatRegistry), args[2].(ChatRoomFactory), args[3].(oscar.SNAC_0x0E_0x02_ChatRoomInfoUpdate))
	})
	return _c
}

func (_c *MockChatNavHandler_CreateRoomHandler_Call) Return(_a0 XMessage, _a1 error) *MockChatNavHandler_CreateRoomHandler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatNavHandler_CreateRoomHandler_Call) RunAndReturn(run func(*Session, *ChatRegistry, ChatRoomFactory, oscar.SNAC_0x0E_0x02_ChatRoomInfoUpdate) (XMessage, error)) *MockChatNavHandler_CreateRoomHandler_Call {
	_c.Call.Return(run)
	return _c
}

// RequestChatRightsHandler provides a mock function with given fields:
func (_m *MockChatNavHandler) RequestChatRightsHandler() XMessage {
	ret := _m.Called()

	var r0 XMessage
	if rf, ok := ret.Get(0).(func() XMessage); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(XMessage)
	}

	return r0
}

// MockChatNavHandler_RequestChatRightsHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestChatRightsHandler'
type MockChatNavHandler_RequestChatRightsHandler_Call struct {
	*mock.Call
}

// RequestChatRightsHandler is a helper method to define mock.On call
func (_e *MockChatNavHandler_Expecter) RequestChatRightsHandler() *MockChatNavHandler_RequestChatRightsHandler_Call {
	return &MockChatNavHandler_RequestChatRightsHandler_Call{Call: _e.mock.On("RequestChatRightsHandler")}
}

func (_c *MockChatNavHandler_RequestChatRightsHandler_Call) Run(run func()) *MockChatNavHandler_RequestChatRightsHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChatNavHandler_RequestChatRightsHandler_Call) Return(_a0 XMessage) *MockChatNavHandler_RequestChatRightsHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatNavHandler_RequestChatRightsHandler_Call) RunAndReturn(run func() XMessage) *MockChatNavHandler_RequestChatRightsHandler_Call {
	_c.Call.Return(run)
	return _c
}

// RequestRoomInfoHandler provides a mock function with given fields: cr, snacPayloadIn
func (_m *MockChatNavHandler) RequestRoomInfoHandler(cr *ChatRegistry, snacPayloadIn oscar.SNAC_0x0D_0x04_ChatNavRequestRoomInfo) (XMessage, error) {
	ret := _m.Called(cr, snacPayloadIn)

	var r0 XMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(*ChatRegistry, oscar.SNAC_0x0D_0x04_ChatNavRequestRoomInfo) (XMessage, error)); ok {
		return rf(cr, snacPayloadIn)
	}
	if rf, ok := ret.Get(0).(func(*ChatRegistry, oscar.SNAC_0x0D_0x04_ChatNavRequestRoomInfo) XMessage); ok {
		r0 = rf(cr, snacPayloadIn)
	} else {
		r0 = ret.Get(0).(XMessage)
	}

	if rf, ok := ret.Get(1).(func(*ChatRegistry, oscar.SNAC_0x0D_0x04_ChatNavRequestRoomInfo) error); ok {
		r1 = rf(cr, snacPayloadIn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatNavHandler_RequestRoomInfoHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestRoomInfoHandler'
type MockChatNavHandler_RequestRoomInfoHandler_Call struct {
	*mock.Call
}

// RequestRoomInfoHandler is a helper method to define mock.On call
//   - cr *ChatRegistry
//   - snacPayloadIn oscar.SNAC_0x0D_0x04_ChatNavRequestRoomInfo
func (_e *MockChatNavHandler_Expecter) RequestRoomInfoHandler(cr interface{}, snacPayloadIn interface{}) *MockChatNavHandler_RequestRoomInfoHandler_Call {
	return &MockChatNavHandler_RequestRoomInfoHandler_Call{Call: _e.mock.On("RequestRoomInfoHandler", cr, snacPayloadIn)}
}

func (_c *MockChatNavHandler_RequestRoomInfoHandler_Call) Run(run func(cr *ChatRegistry, snacPayloadIn oscar.SNAC_0x0D_0x04_ChatNavRequestRoomInfo)) *MockChatNavHandler_RequestRoomInfoHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ChatRegistry), args[1].(oscar.SNAC_0x0D_0x04_ChatNavRequestRoomInfo))
	})
	return _c
}

func (_c *MockChatNavHandler_RequestRoomInfoHandler_Call) Return(_a0 XMessage, _a1 error) *MockChatNavHandler_RequestRoomInfoHandler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatNavHandler_RequestRoomInfoHandler_Call) RunAndReturn(run func(*ChatRegistry, oscar.SNAC_0x0D_0x04_ChatNavRequestRoomInfo) (XMessage, error)) *MockChatNavHandler_RequestRoomInfoHandler_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatNavHandler creates a new instance of MockChatNavHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatNavHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatNavHandler {
	mock := &MockChatNavHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
