// Code generated by mockery v2.35.2. DO NOT EDIT.

package server

import (
	context "context"

	oscar "github.com/mkaminski/goaim/oscar"
	mock "github.com/stretchr/testify/mock"

	state "github.com/mkaminski/goaim/state"
)

// mockOServiceHandler is an autogenerated mock type for the OServiceHandler type
type mockOServiceHandler struct {
	mock.Mock
}

type mockOServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOServiceHandler) EXPECT() *mockOServiceHandler_Expecter {
	return &mockOServiceHandler_Expecter{mock: &_m.Mock}
}

// ClientVersionsHandler provides a mock function with given fields: ctx, frame, bodyIn
func (_m *mockOServiceHandler) ClientVersionsHandler(ctx context.Context, frame oscar.SNACFrame, bodyIn oscar.SNAC_0x01_0x17_OServiceClientVersions) oscar.SNACMessage {
	ret := _m.Called(ctx, frame, bodyIn)

	var r0 oscar.SNACMessage
	if rf, ok := ret.Get(0).(func(context.Context, oscar.SNACFrame, oscar.SNAC_0x01_0x17_OServiceClientVersions) oscar.SNACMessage); ok {
		r0 = rf(ctx, frame, bodyIn)
	} else {
		r0 = ret.Get(0).(oscar.SNACMessage)
	}

	return r0
}

// mockOServiceHandler_ClientVersionsHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientVersionsHandler'
type mockOServiceHandler_ClientVersionsHandler_Call struct {
	*mock.Call
}

// ClientVersionsHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - frame oscar.SNACFrame
//   - bodyIn oscar.SNAC_0x01_0x17_OServiceClientVersions
func (_e *mockOServiceHandler_Expecter) ClientVersionsHandler(ctx interface{}, frame interface{}, bodyIn interface{}) *mockOServiceHandler_ClientVersionsHandler_Call {
	return &mockOServiceHandler_ClientVersionsHandler_Call{Call: _e.mock.On("ClientVersionsHandler", ctx, frame, bodyIn)}
}

func (_c *mockOServiceHandler_ClientVersionsHandler_Call) Run(run func(ctx context.Context, frame oscar.SNACFrame, bodyIn oscar.SNAC_0x01_0x17_OServiceClientVersions)) *mockOServiceHandler_ClientVersionsHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oscar.SNACFrame), args[2].(oscar.SNAC_0x01_0x17_OServiceClientVersions))
	})
	return _c
}

func (_c *mockOServiceHandler_ClientVersionsHandler_Call) Return(_a0 oscar.SNACMessage) *mockOServiceHandler_ClientVersionsHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOServiceHandler_ClientVersionsHandler_Call) RunAndReturn(run func(context.Context, oscar.SNACFrame, oscar.SNAC_0x01_0x17_OServiceClientVersions) oscar.SNACMessage) *mockOServiceHandler_ClientVersionsHandler_Call {
	_c.Call.Return(run)
	return _c
}

// IdleNotificationHandler provides a mock function with given fields: ctx, sess, bodyIn
func (_m *mockOServiceHandler) IdleNotificationHandler(ctx context.Context, sess *state.Session, bodyIn oscar.SNAC_0x01_0x11_OServiceIdleNotification) error {
	ret := _m.Called(ctx, sess, bodyIn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, oscar.SNAC_0x01_0x11_OServiceIdleNotification) error); ok {
		r0 = rf(ctx, sess, bodyIn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockOServiceHandler_IdleNotificationHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdleNotificationHandler'
type mockOServiceHandler_IdleNotificationHandler_Call struct {
	*mock.Call
}

// IdleNotificationHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - bodyIn oscar.SNAC_0x01_0x11_OServiceIdleNotification
func (_e *mockOServiceHandler_Expecter) IdleNotificationHandler(ctx interface{}, sess interface{}, bodyIn interface{}) *mockOServiceHandler_IdleNotificationHandler_Call {
	return &mockOServiceHandler_IdleNotificationHandler_Call{Call: _e.mock.On("IdleNotificationHandler", ctx, sess, bodyIn)}
}

func (_c *mockOServiceHandler_IdleNotificationHandler_Call) Run(run func(ctx context.Context, sess *state.Session, bodyIn oscar.SNAC_0x01_0x11_OServiceIdleNotification)) *mockOServiceHandler_IdleNotificationHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*state.Session), args[2].(oscar.SNAC_0x01_0x11_OServiceIdleNotification))
	})
	return _c
}

func (_c *mockOServiceHandler_IdleNotificationHandler_Call) Return(_a0 error) *mockOServiceHandler_IdleNotificationHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOServiceHandler_IdleNotificationHandler_Call) RunAndReturn(run func(context.Context, *state.Session, oscar.SNAC_0x01_0x11_OServiceIdleNotification) error) *mockOServiceHandler_IdleNotificationHandler_Call {
	_c.Call.Return(run)
	return _c
}

// RateParamsQueryHandler provides a mock function with given fields: ctx, frame
func (_m *mockOServiceHandler) RateParamsQueryHandler(ctx context.Context, frame oscar.SNACFrame) oscar.SNACMessage {
	ret := _m.Called(ctx, frame)

	var r0 oscar.SNACMessage
	if rf, ok := ret.Get(0).(func(context.Context, oscar.SNACFrame) oscar.SNACMessage); ok {
		r0 = rf(ctx, frame)
	} else {
		r0 = ret.Get(0).(oscar.SNACMessage)
	}

	return r0
}

// mockOServiceHandler_RateParamsQueryHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RateParamsQueryHandler'
type mockOServiceHandler_RateParamsQueryHandler_Call struct {
	*mock.Call
}

// RateParamsQueryHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - frame oscar.SNACFrame
func (_e *mockOServiceHandler_Expecter) RateParamsQueryHandler(ctx interface{}, frame interface{}) *mockOServiceHandler_RateParamsQueryHandler_Call {
	return &mockOServiceHandler_RateParamsQueryHandler_Call{Call: _e.mock.On("RateParamsQueryHandler", ctx, frame)}
}

func (_c *mockOServiceHandler_RateParamsQueryHandler_Call) Run(run func(ctx context.Context, frame oscar.SNACFrame)) *mockOServiceHandler_RateParamsQueryHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oscar.SNACFrame))
	})
	return _c
}

func (_c *mockOServiceHandler_RateParamsQueryHandler_Call) Return(_a0 oscar.SNACMessage) *mockOServiceHandler_RateParamsQueryHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOServiceHandler_RateParamsQueryHandler_Call) RunAndReturn(run func(context.Context, oscar.SNACFrame) oscar.SNACMessage) *mockOServiceHandler_RateParamsQueryHandler_Call {
	_c.Call.Return(run)
	return _c
}

// RateParamsSubAddHandler provides a mock function with given fields: _a0, _a1
func (_m *mockOServiceHandler) RateParamsSubAddHandler(_a0 context.Context, _a1 oscar.SNAC_0x01_0x08_OServiceRateParamsSubAdd) {
	_m.Called(_a0, _a1)
}

// mockOServiceHandler_RateParamsSubAddHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RateParamsSubAddHandler'
type mockOServiceHandler_RateParamsSubAddHandler_Call struct {
	*mock.Call
}

// RateParamsSubAddHandler is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 oscar.SNAC_0x01_0x08_OServiceRateParamsSubAdd
func (_e *mockOServiceHandler_Expecter) RateParamsSubAddHandler(_a0 interface{}, _a1 interface{}) *mockOServiceHandler_RateParamsSubAddHandler_Call {
	return &mockOServiceHandler_RateParamsSubAddHandler_Call{Call: _e.mock.On("RateParamsSubAddHandler", _a0, _a1)}
}

func (_c *mockOServiceHandler_RateParamsSubAddHandler_Call) Run(run func(_a0 context.Context, _a1 oscar.SNAC_0x01_0x08_OServiceRateParamsSubAdd)) *mockOServiceHandler_RateParamsSubAddHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oscar.SNAC_0x01_0x08_OServiceRateParamsSubAdd))
	})
	return _c
}

func (_c *mockOServiceHandler_RateParamsSubAddHandler_Call) Return() *mockOServiceHandler_RateParamsSubAddHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockOServiceHandler_RateParamsSubAddHandler_Call) RunAndReturn(run func(context.Context, oscar.SNAC_0x01_0x08_OServiceRateParamsSubAdd)) *mockOServiceHandler_RateParamsSubAddHandler_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserInfoFieldsHandler provides a mock function with given fields: ctx, sess, frame, bodyIn
func (_m *mockOServiceHandler) SetUserInfoFieldsHandler(ctx context.Context, sess *state.Session, frame oscar.SNACFrame, bodyIn oscar.SNAC_0x01_0x1E_OServiceSetUserInfoFields) (oscar.SNACMessage, error) {
	ret := _m.Called(ctx, sess, frame, bodyIn)

	var r0 oscar.SNACMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x01_0x1E_OServiceSetUserInfoFields) (oscar.SNACMessage, error)); ok {
		return rf(ctx, sess, frame, bodyIn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x01_0x1E_OServiceSetUserInfoFields) oscar.SNACMessage); ok {
		r0 = rf(ctx, sess, frame, bodyIn)
	} else {
		r0 = ret.Get(0).(oscar.SNACMessage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x01_0x1E_OServiceSetUserInfoFields) error); ok {
		r1 = rf(ctx, sess, frame, bodyIn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOServiceHandler_SetUserInfoFieldsHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserInfoFieldsHandler'
type mockOServiceHandler_SetUserInfoFieldsHandler_Call struct {
	*mock.Call
}

// SetUserInfoFieldsHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - frame oscar.SNACFrame
//   - bodyIn oscar.SNAC_0x01_0x1E_OServiceSetUserInfoFields
func (_e *mockOServiceHandler_Expecter) SetUserInfoFieldsHandler(ctx interface{}, sess interface{}, frame interface{}, bodyIn interface{}) *mockOServiceHandler_SetUserInfoFieldsHandler_Call {
	return &mockOServiceHandler_SetUserInfoFieldsHandler_Call{Call: _e.mock.On("SetUserInfoFieldsHandler", ctx, sess, frame, bodyIn)}
}

func (_c *mockOServiceHandler_SetUserInfoFieldsHandler_Call) Run(run func(ctx context.Context, sess *state.Session, frame oscar.SNACFrame, bodyIn oscar.SNAC_0x01_0x1E_OServiceSetUserInfoFields)) *mockOServiceHandler_SetUserInfoFieldsHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*state.Session), args[2].(oscar.SNACFrame), args[3].(oscar.SNAC_0x01_0x1E_OServiceSetUserInfoFields))
	})
	return _c
}

func (_c *mockOServiceHandler_SetUserInfoFieldsHandler_Call) Return(_a0 oscar.SNACMessage, _a1 error) *mockOServiceHandler_SetUserInfoFieldsHandler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOServiceHandler_SetUserInfoFieldsHandler_Call) RunAndReturn(run func(context.Context, *state.Session, oscar.SNACFrame, oscar.SNAC_0x01_0x1E_OServiceSetUserInfoFields) (oscar.SNACMessage, error)) *mockOServiceHandler_SetUserInfoFieldsHandler_Call {
	_c.Call.Return(run)
	return _c
}

// UserInfoQueryHandler provides a mock function with given fields: ctx, sess, frame
func (_m *mockOServiceHandler) UserInfoQueryHandler(ctx context.Context, sess *state.Session, frame oscar.SNACFrame) oscar.SNACMessage {
	ret := _m.Called(ctx, sess, frame)

	var r0 oscar.SNACMessage
	if rf, ok := ret.Get(0).(func(context.Context, *state.Session, oscar.SNACFrame) oscar.SNACMessage); ok {
		r0 = rf(ctx, sess, frame)
	} else {
		r0 = ret.Get(0).(oscar.SNACMessage)
	}

	return r0
}

// mockOServiceHandler_UserInfoQueryHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserInfoQueryHandler'
type mockOServiceHandler_UserInfoQueryHandler_Call struct {
	*mock.Call
}

// UserInfoQueryHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
//   - frame oscar.SNACFrame
func (_e *mockOServiceHandler_Expecter) UserInfoQueryHandler(ctx interface{}, sess interface{}, frame interface{}) *mockOServiceHandler_UserInfoQueryHandler_Call {
	return &mockOServiceHandler_UserInfoQueryHandler_Call{Call: _e.mock.On("UserInfoQueryHandler", ctx, sess, frame)}
}

func (_c *mockOServiceHandler_UserInfoQueryHandler_Call) Run(run func(ctx context.Context, sess *state.Session, frame oscar.SNACFrame)) *mockOServiceHandler_UserInfoQueryHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*state.Session), args[2].(oscar.SNACFrame))
	})
	return _c
}

func (_c *mockOServiceHandler_UserInfoQueryHandler_Call) Return(_a0 oscar.SNACMessage) *mockOServiceHandler_UserInfoQueryHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOServiceHandler_UserInfoQueryHandler_Call) RunAndReturn(run func(context.Context, *state.Session, oscar.SNACFrame) oscar.SNACMessage) *mockOServiceHandler_UserInfoQueryHandler_Call {
	_c.Call.Return(run)
	return _c
}

// newMockOServiceHandler creates a new instance of mockOServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOServiceHandler {
	mock := &mockOServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
