// Code generated by mockery v2.34.2. DO NOT EDIT.

package server

import mock "github.com/stretchr/testify/mock"

// MockProfileManager is an autogenerated mock type for the ProfileManager type
type MockProfileManager struct {
	mock.Mock
}

type MockProfileManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileManager) EXPECT() *MockProfileManager_Expecter {
	return &MockProfileManager_Expecter{mock: &_m.Mock}
}

// RetrieveProfile provides a mock function with given fields: screenName
func (_m *MockProfileManager) RetrieveProfile(screenName string) (string, error) {
	ret := _m.Called(screenName)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(screenName)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(screenName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(screenName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProfileManager_RetrieveProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveProfile'
type MockProfileManager_RetrieveProfile_Call struct {
	*mock.Call
}

// RetrieveProfile is a helper method to define mock.On call
//   - screenName string
func (_e *MockProfileManager_Expecter) RetrieveProfile(screenName interface{}) *MockProfileManager_RetrieveProfile_Call {
	return &MockProfileManager_RetrieveProfile_Call{Call: _e.mock.On("RetrieveProfile", screenName)}
}

func (_c *MockProfileManager_RetrieveProfile_Call) Run(run func(screenName string)) *MockProfileManager_RetrieveProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockProfileManager_RetrieveProfile_Call) Return(_a0 string, _a1 error) *MockProfileManager_RetrieveProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProfileManager_RetrieveProfile_Call) RunAndReturn(run func(string) (string, error)) *MockProfileManager_RetrieveProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertProfile provides a mock function with given fields: screenName, body
func (_m *MockProfileManager) UpsertProfile(screenName string, body string) error {
	ret := _m.Called(screenName, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(screenName, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProfileManager_UpsertProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertProfile'
type MockProfileManager_UpsertProfile_Call struct {
	*mock.Call
}

// UpsertProfile is a helper method to define mock.On call
//   - screenName string
//   - body string
func (_e *MockProfileManager_Expecter) UpsertProfile(screenName interface{}, body interface{}) *MockProfileManager_UpsertProfile_Call {
	return &MockProfileManager_UpsertProfile_Call{Call: _e.mock.On("UpsertProfile", screenName, body)}
}

func (_c *MockProfileManager_UpsertProfile_Call) Run(run func(screenName string, body string)) *MockProfileManager_UpsertProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockProfileManager_UpsertProfile_Call) Return(_a0 error) *MockProfileManager_UpsertProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProfileManager_UpsertProfile_Call) RunAndReturn(run func(string, string) error) *MockProfileManager_UpsertProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileManager creates a new instance of MockProfileManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileManager {
	mock := &MockProfileManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
