// Code generated by mockery v2.34.2. DO NOT EDIT.

package server

import (
	context "context"

	oscar "github.com/mkaminski/goaim/oscar"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionManager is an autogenerated mock type for the SessionManager type
type MockSessionManager struct {
	mock.Mock
}

type MockSessionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionManager) EXPECT() *MockSessionManager_Expecter {
	return &MockSessionManager_Expecter{mock: &_m.Mock}
}

// Broadcast provides a mock function with given fields: ctx, msg
func (_m *MockSessionManager) Broadcast(ctx context.Context, msg oscar.XMessage) {
	_m.Called(ctx, msg)
}

// MockSessionManager_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type MockSessionManager_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - ctx context.Context
//   - msg oscar.XMessage
func (_e *MockSessionManager_Expecter) Broadcast(ctx interface{}, msg interface{}) *MockSessionManager_Broadcast_Call {
	return &MockSessionManager_Broadcast_Call{Call: _e.mock.On("Broadcast", ctx, msg)}
}

func (_c *MockSessionManager_Broadcast_Call) Run(run func(ctx context.Context, msg oscar.XMessage)) *MockSessionManager_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oscar.XMessage))
	})
	return _c
}

func (_c *MockSessionManager_Broadcast_Call) Return() *MockSessionManager_Broadcast_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionManager_Broadcast_Call) RunAndReturn(run func(context.Context, oscar.XMessage)) *MockSessionManager_Broadcast_Call {
	_c.Call.Return(run)
	return _c
}

// BroadcastToScreenNames provides a mock function with given fields: ctx, screenNames, msg
func (_m *MockSessionManager) BroadcastToScreenNames(ctx context.Context, screenNames []string, msg oscar.XMessage) {
	_m.Called(ctx, screenNames, msg)
}

// MockSessionManager_BroadcastToScreenNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastToScreenNames'
type MockSessionManager_BroadcastToScreenNames_Call struct {
	*mock.Call
}

// BroadcastToScreenNames is a helper method to define mock.On call
//   - ctx context.Context
//   - screenNames []string
//   - msg oscar.XMessage
func (_e *MockSessionManager_Expecter) BroadcastToScreenNames(ctx interface{}, screenNames interface{}, msg interface{}) *MockSessionManager_BroadcastToScreenNames_Call {
	return &MockSessionManager_BroadcastToScreenNames_Call{Call: _e.mock.On("BroadcastToScreenNames", ctx, screenNames, msg)}
}

func (_c *MockSessionManager_BroadcastToScreenNames_Call) Run(run func(ctx context.Context, screenNames []string, msg oscar.XMessage)) *MockSessionManager_BroadcastToScreenNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(oscar.XMessage))
	})
	return _c
}

func (_c *MockSessionManager_BroadcastToScreenNames_Call) Return() *MockSessionManager_BroadcastToScreenNames_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionManager_BroadcastToScreenNames_Call) RunAndReturn(run func(context.Context, []string, oscar.XMessage)) *MockSessionManager_BroadcastToScreenNames_Call {
	_c.Call.Return(run)
	return _c
}

// Empty provides a mock function with given fields:
func (_m *MockSessionManager) Empty() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockSessionManager_Empty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Empty'
type MockSessionManager_Empty_Call struct {
	*mock.Call
}

// Empty is a helper method to define mock.On call
func (_e *MockSessionManager_Expecter) Empty() *MockSessionManager_Empty_Call {
	return &MockSessionManager_Empty_Call{Call: _e.mock.On("Empty")}
}

func (_c *MockSessionManager_Empty_Call) Run(run func()) *MockSessionManager_Empty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionManager_Empty_Call) Return(_a0 bool) *MockSessionManager_Empty_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionManager_Empty_Call) RunAndReturn(run func() bool) *MockSessionManager_Empty_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionWithSN provides a mock function with given fields: sessID, screenName
func (_m *MockSessionManager) NewSessionWithSN(sessID string, screenName string) *Session {
	ret := _m.Called(sessID, screenName)

	var r0 *Session
	if rf, ok := ret.Get(0).(func(string, string) *Session); ok {
		r0 = rf(sessID, screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Session)
		}
	}

	return r0
}

// MockSessionManager_NewSessionWithSN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewSessionWithSN'
type MockSessionManager_NewSessionWithSN_Call struct {
	*mock.Call
}

// NewSessionWithSN is a helper method to define mock.On call
//   - sessID string
//   - screenName string
func (_e *MockSessionManager_Expecter) NewSessionWithSN(sessID interface{}, screenName interface{}) *MockSessionManager_NewSessionWithSN_Call {
	return &MockSessionManager_NewSessionWithSN_Call{Call: _e.mock.On("NewSessionWithSN", sessID, screenName)}
}

func (_c *MockSessionManager_NewSessionWithSN_Call) Run(run func(sessID string, screenName string)) *MockSessionManager_NewSessionWithSN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSessionManager_NewSessionWithSN_Call) Return(_a0 *Session) *MockSessionManager_NewSessionWithSN_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionManager_NewSessionWithSN_Call) RunAndReturn(run func(string, string) *Session) *MockSessionManager_NewSessionWithSN_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: sess
func (_m *MockSessionManager) Remove(sess *Session) {
	_m.Called(sess)
}

// MockSessionManager_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockSessionManager_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - sess *Session
func (_e *MockSessionManager_Expecter) Remove(sess interface{}) *MockSessionManager_Remove_Call {
	return &MockSessionManager_Remove_Call{Call: _e.mock.On("Remove", sess)}
}

func (_c *MockSessionManager_Remove_Call) Run(run func(sess *Session)) *MockSessionManager_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Session))
	})
	return _c
}

func (_c *MockSessionManager_Remove_Call) Return() *MockSessionManager_Remove_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionManager_Remove_Call) RunAndReturn(run func(*Session)) *MockSessionManager_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function with given fields: ID
func (_m *MockSessionManager) Retrieve(ID string) (*Session, bool) {
	ret := _m.Called(ID)

	var r0 *Session
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*Session, bool)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(string) *Session); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockSessionManager_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type MockSessionManager_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ID string
func (_e *MockSessionManager_Expecter) Retrieve(ID interface{}) *MockSessionManager_Retrieve_Call {
	return &MockSessionManager_Retrieve_Call{Call: _e.mock.On("Retrieve", ID)}
}

func (_c *MockSessionManager_Retrieve_Call) Run(run func(ID string)) *MockSessionManager_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionManager_Retrieve_Call) Return(_a0 *Session, _a1 bool) *MockSessionManager_Retrieve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionManager_Retrieve_Call) RunAndReturn(run func(string) (*Session, bool)) *MockSessionManager_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveByScreenName provides a mock function with given fields: screenName
func (_m *MockSessionManager) RetrieveByScreenName(screenName string) *Session {
	ret := _m.Called(screenName)

	var r0 *Session
	if rf, ok := ret.Get(0).(func(string) *Session); ok {
		r0 = rf(screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Session)
		}
	}

	return r0
}

// MockSessionManager_RetrieveByScreenName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveByScreenName'
type MockSessionManager_RetrieveByScreenName_Call struct {
	*mock.Call
}

// RetrieveByScreenName is a helper method to define mock.On call
//   - screenName string
func (_e *MockSessionManager_Expecter) RetrieveByScreenName(screenName interface{}) *MockSessionManager_RetrieveByScreenName_Call {
	return &MockSessionManager_RetrieveByScreenName_Call{Call: _e.mock.On("RetrieveByScreenName", screenName)}
}

func (_c *MockSessionManager_RetrieveByScreenName_Call) Run(run func(screenName string)) *MockSessionManager_RetrieveByScreenName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionManager_RetrieveByScreenName_Call) Return(_a0 *Session) *MockSessionManager_RetrieveByScreenName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionManager_RetrieveByScreenName_Call) RunAndReturn(run func(string) *Session) *MockSessionManager_RetrieveByScreenName_Call {
	_c.Call.Return(run)
	return _c
}

// SendToScreenName provides a mock function with given fields: ctx, screenName, msg
func (_m *MockSessionManager) SendToScreenName(ctx context.Context, screenName string, msg oscar.XMessage) {
	_m.Called(ctx, screenName, msg)
}

// MockSessionManager_SendToScreenName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendToScreenName'
type MockSessionManager_SendToScreenName_Call struct {
	*mock.Call
}

// SendToScreenName is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName string
//   - msg oscar.XMessage
func (_e *MockSessionManager_Expecter) SendToScreenName(ctx interface{}, screenName interface{}, msg interface{}) *MockSessionManager_SendToScreenName_Call {
	return &MockSessionManager_SendToScreenName_Call{Call: _e.mock.On("SendToScreenName", ctx, screenName, msg)}
}

func (_c *MockSessionManager_SendToScreenName_Call) Run(run func(ctx context.Context, screenName string, msg oscar.XMessage)) *MockSessionManager_SendToScreenName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(oscar.XMessage))
	})
	return _c
}

func (_c *MockSessionManager_SendToScreenName_Call) Return() *MockSessionManager_SendToScreenName_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionManager_SendToScreenName_Call) RunAndReturn(run func(context.Context, string, oscar.XMessage)) *MockSessionManager_SendToScreenName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionManager creates a new instance of MockSessionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionManager {
	mock := &MockSessionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
