// Code generated by mockery v2.53.3. DO NOT EDIT.

package foodgroup

import (
	context "context"

	state "github.com/mk6i/retro-aim-server/state"
	mock "github.com/stretchr/testify/mock"

	wire "github.com/mk6i/retro-aim-server/wire"
)

// mockBARTItemManager is an autogenerated mock type for the BARTItemManager type
type mockBARTItemManager struct {
	mock.Mock
}

type mockBARTItemManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBARTItemManager) EXPECT() *mockBARTItemManager_Expecter {
	return &mockBARTItemManager_Expecter{mock: &_m.Mock}
}

// BARTItem provides a mock function with given fields: ctx, hash
func (_m *mockBARTItemManager) BARTItem(ctx context.Context, hash []byte) ([]byte, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for BARTItem")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBARTItemManager_BARTItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BARTItem'
type mockBARTItemManager_BARTItem_Call struct {
	*mock.Call
}

// BARTItem is a helper method to define mock.On call
//   - ctx context.Context
//   - hash []byte
func (_e *mockBARTItemManager_Expecter) BARTItem(ctx interface{}, hash interface{}) *mockBARTItemManager_BARTItem_Call {
	return &mockBARTItemManager_BARTItem_Call{Call: _e.mock.On("BARTItem", ctx, hash)}
}

func (_c *mockBARTItemManager_BARTItem_Call) Run(run func(ctx context.Context, hash []byte)) *mockBARTItemManager_BARTItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *mockBARTItemManager_BARTItem_Call) Return(_a0 []byte, _a1 error) *mockBARTItemManager_BARTItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBARTItemManager_BARTItem_Call) RunAndReturn(run func(context.Context, []byte) ([]byte, error)) *mockBARTItemManager_BARTItem_Call {
	_c.Call.Return(run)
	return _c
}

// BuddyIconMetadata provides a mock function with given fields: ctx, screenName
func (_m *mockBARTItemManager) BuddyIconMetadata(ctx context.Context, screenName state.IdentScreenName) (*wire.BARTID, error) {
	ret := _m.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for BuddyIconMetadata")
	}

	var r0 *wire.BARTID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) (*wire.BARTID, error)); ok {
		return rf(ctx, screenName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) *wire.BARTID); ok {
		r0 = rf(ctx, screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wire.BARTID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, state.IdentScreenName) error); ok {
		r1 = rf(ctx, screenName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBARTItemManager_BuddyIconMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuddyIconMetadata'
type mockBARTItemManager_BuddyIconMetadata_Call struct {
	*mock.Call
}

// BuddyIconMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockBARTItemManager_Expecter) BuddyIconMetadata(ctx interface{}, screenName interface{}) *mockBARTItemManager_BuddyIconMetadata_Call {
	return &mockBARTItemManager_BuddyIconMetadata_Call{Call: _e.mock.On("BuddyIconMetadata", ctx, screenName)}
}

func (_c *mockBARTItemManager_BuddyIconMetadata_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockBARTItemManager_BuddyIconMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(state.IdentScreenName))
	})
	return _c
}

func (_c *mockBARTItemManager_BuddyIconMetadata_Call) Return(_a0 *wire.BARTID, _a1 error) *mockBARTItemManager_BuddyIconMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBARTItemManager_BuddyIconMetadata_Call) RunAndReturn(run func(context.Context, state.IdentScreenName) (*wire.BARTID, error)) *mockBARTItemManager_BuddyIconMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBARTItem provides a mock function with given fields: ctx, hash
func (_m *mockBARTItemManager) DeleteBARTItem(ctx context.Context, hash []byte) error {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBARTItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockBARTItemManager_DeleteBARTItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBARTItem'
type mockBARTItemManager_DeleteBARTItem_Call struct {
	*mock.Call
}

// DeleteBARTItem is a helper method to define mock.On call
//   - ctx context.Context
//   - hash []byte
func (_e *mockBARTItemManager_Expecter) DeleteBARTItem(ctx interface{}, hash interface{}) *mockBARTItemManager_DeleteBARTItem_Call {
	return &mockBARTItemManager_DeleteBARTItem_Call{Call: _e.mock.On("DeleteBARTItem", ctx, hash)}
}

func (_c *mockBARTItemManager_DeleteBARTItem_Call) Run(run func(ctx context.Context, hash []byte)) *mockBARTItemManager_DeleteBARTItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *mockBARTItemManager_DeleteBARTItem_Call) Return(_a0 error) *mockBARTItemManager_DeleteBARTItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockBARTItemManager_DeleteBARTItem_Call) RunAndReturn(run func(context.Context, []byte) error) *mockBARTItemManager_DeleteBARTItem_Call {
	_c.Call.Return(run)
	return _c
}

// InsertBARTItem provides a mock function with given fields: ctx, hash, blob, itemType
func (_m *mockBARTItemManager) InsertBARTItem(ctx context.Context, hash []byte, blob []byte, itemType uint16) error {
	ret := _m.Called(ctx, hash, blob, itemType)

	if len(ret) == 0 {
		panic("no return value specified for InsertBARTItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte, uint16) error); ok {
		r0 = rf(ctx, hash, blob, itemType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockBARTItemManager_InsertBARTItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertBARTItem'
type mockBARTItemManager_InsertBARTItem_Call struct {
	*mock.Call
}

// InsertBARTItem is a helper method to define mock.On call
//   - ctx context.Context
//   - hash []byte
//   - blob []byte
//   - itemType uint16
func (_e *mockBARTItemManager_Expecter) InsertBARTItem(ctx interface{}, hash interface{}, blob interface{}, itemType interface{}) *mockBARTItemManager_InsertBARTItem_Call {
	return &mockBARTItemManager_InsertBARTItem_Call{Call: _e.mock.On("InsertBARTItem", ctx, hash, blob, itemType)}
}

func (_c *mockBARTItemManager_InsertBARTItem_Call) Run(run func(ctx context.Context, hash []byte, blob []byte, itemType uint16)) *mockBARTItemManager_InsertBARTItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].([]byte), args[3].(uint16))
	})
	return _c
}

func (_c *mockBARTItemManager_InsertBARTItem_Call) Return(_a0 error) *mockBARTItemManager_InsertBARTItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockBARTItemManager_InsertBARTItem_Call) RunAndReturn(run func(context.Context, []byte, []byte, uint16) error) *mockBARTItemManager_InsertBARTItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListBARTItems provides a mock function with given fields: ctx, itemType
func (_m *mockBARTItemManager) ListBARTItems(ctx context.Context, itemType uint16) ([]state.BARTItem, error) {
	ret := _m.Called(ctx, itemType)

	if len(ret) == 0 {
		panic("no return value specified for ListBARTItems")
	}

	var r0 []state.BARTItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint16) ([]state.BARTItem, error)); ok {
		return rf(ctx, itemType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint16) []state.BARTItem); ok {
		r0 = rf(ctx, itemType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]state.BARTItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint16) error); ok {
		r1 = rf(ctx, itemType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBARTItemManager_ListBARTItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBARTItems'
type mockBARTItemManager_ListBARTItems_Call struct {
	*mock.Call
}

// ListBARTItems is a helper method to define mock.On call
//   - ctx context.Context
//   - itemType uint16
func (_e *mockBARTItemManager_Expecter) ListBARTItems(ctx interface{}, itemType interface{}) *mockBARTItemManager_ListBARTItems_Call {
	return &mockBARTItemManager_ListBARTItems_Call{Call: _e.mock.On("ListBARTItems", ctx, itemType)}
}

func (_c *mockBARTItemManager_ListBARTItems_Call) Run(run func(ctx context.Context, itemType uint16)) *mockBARTItemManager_ListBARTItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint16))
	})
	return _c
}

func (_c *mockBARTItemManager_ListBARTItems_Call) Return(_a0 []state.BARTItem, _a1 error) *mockBARTItemManager_ListBARTItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBARTItemManager_ListBARTItems_Call) RunAndReturn(run func(context.Context, uint16) ([]state.BARTItem, error)) *mockBARTItemManager_ListBARTItems_Call {
	_c.Call.Return(run)
	return _c
}

// newMockBARTItemManager creates a new instance of mockBARTItemManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBARTItemManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBARTItemManager {
	mock := &mockBARTItemManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
