// Code generated by mockery v2.52.1. DO NOT EDIT.

package foodgroup

import (
	context "context"

	state "github.com/mk6i/retro-aim-server/state"
	mock "github.com/stretchr/testify/mock"

	wire "github.com/mk6i/retro-aim-server/wire"
)

// mockClientSideBuddyListManager is an autogenerated mock type for the ClientSideBuddyListManager type
type mockClientSideBuddyListManager struct {
	mock.Mock
}

type mockClientSideBuddyListManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockClientSideBuddyListManager) EXPECT() *mockClientSideBuddyListManager_Expecter {
	return &mockClientSideBuddyListManager_Expecter{mock: &_m.Mock}
}

// AddBuddy provides a mock function with given fields: ctx, me, them
func (_m *mockClientSideBuddyListManager) AddBuddy(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName) error {
	ret := _m.Called(ctx, me, them)

	if len(ret) == 0 {
		panic("no return value specified for AddBuddy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r0 = rf(ctx, me, them)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockClientSideBuddyListManager_AddBuddy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBuddy'
type mockClientSideBuddyListManager_AddBuddy_Call struct {
	*mock.Call
}

// AddBuddy is a helper method to define mock.On call
//   - ctx context.Context
//   - me state.IdentScreenName
//   - them state.IdentScreenName
func (_e *mockClientSideBuddyListManager_Expecter) AddBuddy(ctx interface{}, me interface{}, them interface{}) *mockClientSideBuddyListManager_AddBuddy_Call {
	return &mockClientSideBuddyListManager_AddBuddy_Call{Call: _e.mock.On("AddBuddy", ctx, me, them)}
}

func (_c *mockClientSideBuddyListManager_AddBuddy_Call) Run(run func(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName)) *mockClientSideBuddyListManager_AddBuddy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(state.IdentScreenName), args[2].(state.IdentScreenName))
	})
	return _c
}

func (_c *mockClientSideBuddyListManager_AddBuddy_Call) Return(_a0 error) *mockClientSideBuddyListManager_AddBuddy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockClientSideBuddyListManager_AddBuddy_Call) RunAndReturn(run func(context.Context, state.IdentScreenName, state.IdentScreenName) error) *mockClientSideBuddyListManager_AddBuddy_Call {
	_c.Call.Return(run)
	return _c
}

// DenyBuddy provides a mock function with given fields: ctx, me, them
func (_m *mockClientSideBuddyListManager) DenyBuddy(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName) error {
	ret := _m.Called(ctx, me, them)

	if len(ret) == 0 {
		panic("no return value specified for DenyBuddy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r0 = rf(ctx, me, them)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockClientSideBuddyListManager_DenyBuddy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DenyBuddy'
type mockClientSideBuddyListManager_DenyBuddy_Call struct {
	*mock.Call
}

// DenyBuddy is a helper method to define mock.On call
//   - ctx context.Context
//   - me state.IdentScreenName
//   - them state.IdentScreenName
func (_e *mockClientSideBuddyListManager_Expecter) DenyBuddy(ctx interface{}, me interface{}, them interface{}) *mockClientSideBuddyListManager_DenyBuddy_Call {
	return &mockClientSideBuddyListManager_DenyBuddy_Call{Call: _e.mock.On("DenyBuddy", ctx, me, them)}
}

func (_c *mockClientSideBuddyListManager_DenyBuddy_Call) Run(run func(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName)) *mockClientSideBuddyListManager_DenyBuddy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(state.IdentScreenName), args[2].(state.IdentScreenName))
	})
	return _c
}

func (_c *mockClientSideBuddyListManager_DenyBuddy_Call) Return(_a0 error) *mockClientSideBuddyListManager_DenyBuddy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockClientSideBuddyListManager_DenyBuddy_Call) RunAndReturn(run func(context.Context, state.IdentScreenName, state.IdentScreenName) error) *mockClientSideBuddyListManager_DenyBuddy_Call {
	_c.Call.Return(run)
	return _c
}

// PermitBuddy provides a mock function with given fields: ctx, me, them
func (_m *mockClientSideBuddyListManager) PermitBuddy(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName) error {
	ret := _m.Called(ctx, me, them)

	if len(ret) == 0 {
		panic("no return value specified for PermitBuddy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r0 = rf(ctx, me, them)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockClientSideBuddyListManager_PermitBuddy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PermitBuddy'
type mockClientSideBuddyListManager_PermitBuddy_Call struct {
	*mock.Call
}

// PermitBuddy is a helper method to define mock.On call
//   - ctx context.Context
//   - me state.IdentScreenName
//   - them state.IdentScreenName
func (_e *mockClientSideBuddyListManager_Expecter) PermitBuddy(ctx interface{}, me interface{}, them interface{}) *mockClientSideBuddyListManager_PermitBuddy_Call {
	return &mockClientSideBuddyListManager_PermitBuddy_Call{Call: _e.mock.On("PermitBuddy", ctx, me, them)}
}

func (_c *mockClientSideBuddyListManager_PermitBuddy_Call) Run(run func(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName)) *mockClientSideBuddyListManager_PermitBuddy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(state.IdentScreenName), args[2].(state.IdentScreenName))
	})
	return _c
}

func (_c *mockClientSideBuddyListManager_PermitBuddy_Call) Return(_a0 error) *mockClientSideBuddyListManager_PermitBuddy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockClientSideBuddyListManager_PermitBuddy_Call) RunAndReturn(run func(context.Context, state.IdentScreenName, state.IdentScreenName) error) *mockClientSideBuddyListManager_PermitBuddy_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveBuddy provides a mock function with given fields: ctx, me, them
func (_m *mockClientSideBuddyListManager) RemoveBuddy(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName) error {
	ret := _m.Called(ctx, me, them)

	if len(ret) == 0 {
		panic("no return value specified for RemoveBuddy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r0 = rf(ctx, me, them)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockClientSideBuddyListManager_RemoveBuddy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveBuddy'
type mockClientSideBuddyListManager_RemoveBuddy_Call struct {
	*mock.Call
}

// RemoveBuddy is a helper method to define mock.On call
//   - ctx context.Context
//   - me state.IdentScreenName
//   - them state.IdentScreenName
func (_e *mockClientSideBuddyListManager_Expecter) RemoveBuddy(ctx interface{}, me interface{}, them interface{}) *mockClientSideBuddyListManager_RemoveBuddy_Call {
	return &mockClientSideBuddyListManager_RemoveBuddy_Call{Call: _e.mock.On("RemoveBuddy", ctx, me, them)}
}

func (_c *mockClientSideBuddyListManager_RemoveBuddy_Call) Run(run func(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName)) *mockClientSideBuddyListManager_RemoveBuddy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(state.IdentScreenName), args[2].(state.IdentScreenName))
	})
	return _c
}

func (_c *mockClientSideBuddyListManager_RemoveBuddy_Call) Return(_a0 error) *mockClientSideBuddyListManager_RemoveBuddy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockClientSideBuddyListManager_RemoveBuddy_Call) RunAndReturn(run func(context.Context, state.IdentScreenName, state.IdentScreenName) error) *mockClientSideBuddyListManager_RemoveBuddy_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveDenyBuddy provides a mock function with given fields: ctx, me, them
func (_m *mockClientSideBuddyListManager) RemoveDenyBuddy(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName) error {
	ret := _m.Called(ctx, me, them)

	if len(ret) == 0 {
		panic("no return value specified for RemoveDenyBuddy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r0 = rf(ctx, me, them)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockClientSideBuddyListManager_RemoveDenyBuddy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveDenyBuddy'
type mockClientSideBuddyListManager_RemoveDenyBuddy_Call struct {
	*mock.Call
}

// RemoveDenyBuddy is a helper method to define mock.On call
//   - ctx context.Context
//   - me state.IdentScreenName
//   - them state.IdentScreenName
func (_e *mockClientSideBuddyListManager_Expecter) RemoveDenyBuddy(ctx interface{}, me interface{}, them interface{}) *mockClientSideBuddyListManager_RemoveDenyBuddy_Call {
	return &mockClientSideBuddyListManager_RemoveDenyBuddy_Call{Call: _e.mock.On("RemoveDenyBuddy", ctx, me, them)}
}

func (_c *mockClientSideBuddyListManager_RemoveDenyBuddy_Call) Run(run func(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName)) *mockClientSideBuddyListManager_RemoveDenyBuddy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(state.IdentScreenName), args[2].(state.IdentScreenName))
	})
	return _c
}

func (_c *mockClientSideBuddyListManager_RemoveDenyBuddy_Call) Return(_a0 error) *mockClientSideBuddyListManager_RemoveDenyBuddy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockClientSideBuddyListManager_RemoveDenyBuddy_Call) RunAndReturn(run func(context.Context, state.IdentScreenName, state.IdentScreenName) error) *mockClientSideBuddyListManager_RemoveDenyBuddy_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePermitBuddy provides a mock function with given fields: ctx, me, them
func (_m *mockClientSideBuddyListManager) RemovePermitBuddy(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName) error {
	ret := _m.Called(ctx, me, them)

	if len(ret) == 0 {
		panic("no return value specified for RemovePermitBuddy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, state.IdentScreenName) error); ok {
		r0 = rf(ctx, me, them)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockClientSideBuddyListManager_RemovePermitBuddy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePermitBuddy'
type mockClientSideBuddyListManager_RemovePermitBuddy_Call struct {
	*mock.Call
}

// RemovePermitBuddy is a helper method to define mock.On call
//   - ctx context.Context
//   - me state.IdentScreenName
//   - them state.IdentScreenName
func (_e *mockClientSideBuddyListManager_Expecter) RemovePermitBuddy(ctx interface{}, me interface{}, them interface{}) *mockClientSideBuddyListManager_RemovePermitBuddy_Call {
	return &mockClientSideBuddyListManager_RemovePermitBuddy_Call{Call: _e.mock.On("RemovePermitBuddy", ctx, me, them)}
}

func (_c *mockClientSideBuddyListManager_RemovePermitBuddy_Call) Run(run func(ctx context.Context, me state.IdentScreenName, them state.IdentScreenName)) *mockClientSideBuddyListManager_RemovePermitBuddy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(state.IdentScreenName), args[2].(state.IdentScreenName))
	})
	return _c
}

func (_c *mockClientSideBuddyListManager_RemovePermitBuddy_Call) Return(_a0 error) *mockClientSideBuddyListManager_RemovePermitBuddy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockClientSideBuddyListManager_RemovePermitBuddy_Call) RunAndReturn(run func(context.Context, state.IdentScreenName, state.IdentScreenName) error) *mockClientSideBuddyListManager_RemovePermitBuddy_Call {
	_c.Call.Return(run)
	return _c
}

// SetPDMode provides a mock function with given fields: ctx, me, pdMode
func (_m *mockClientSideBuddyListManager) SetPDMode(ctx context.Context, me state.IdentScreenName, pdMode wire.FeedbagPDMode) error {
	ret := _m.Called(ctx, me, pdMode)

	if len(ret) == 0 {
		panic("no return value specified for SetPDMode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, wire.FeedbagPDMode) error); ok {
		r0 = rf(ctx, me, pdMode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockClientSideBuddyListManager_SetPDMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPDMode'
type mockClientSideBuddyListManager_SetPDMode_Call struct {
	*mock.Call
}

// SetPDMode is a helper method to define mock.On call
//   - ctx context.Context
//   - me state.IdentScreenName
//   - pdMode wire.FeedbagPDMode
func (_e *mockClientSideBuddyListManager_Expecter) SetPDMode(ctx interface{}, me interface{}, pdMode interface{}) *mockClientSideBuddyListManager_SetPDMode_Call {
	return &mockClientSideBuddyListManager_SetPDMode_Call{Call: _e.mock.On("SetPDMode", ctx, me, pdMode)}
}

func (_c *mockClientSideBuddyListManager_SetPDMode_Call) Run(run func(ctx context.Context, me state.IdentScreenName, pdMode wire.FeedbagPDMode)) *mockClientSideBuddyListManager_SetPDMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(state.IdentScreenName), args[2].(wire.FeedbagPDMode))
	})
	return _c
}

func (_c *mockClientSideBuddyListManager_SetPDMode_Call) Return(_a0 error) *mockClientSideBuddyListManager_SetPDMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockClientSideBuddyListManager_SetPDMode_Call) RunAndReturn(run func(context.Context, state.IdentScreenName, wire.FeedbagPDMode) error) *mockClientSideBuddyListManager_SetPDMode_Call {
	_c.Call.Return(run)
	return _c
}

// newMockClientSideBuddyListManager creates a new instance of mockClientSideBuddyListManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockClientSideBuddyListManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockClientSideBuddyListManager {
	mock := &mockClientSideBuddyListManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
