// Code generated by mockery v2.34.2. DO NOT EDIT.

package handler

import (
	context "context"

	oscar "github.com/mkaminski/goaim/oscar"
	mock "github.com/stretchr/testify/mock"

	state "github.com/mkaminski/goaim/state"
)

// mockChatSessionManager is an autogenerated mock type for the ChatSessionManager type
type mockChatSessionManager struct {
	mock.Mock
}

type mockChatSessionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockChatSessionManager) EXPECT() *mockChatSessionManager_Expecter {
	return &mockChatSessionManager_Expecter{mock: &_m.Mock}
}

// Broadcast provides a mock function with given fields: ctx, msg
func (_m *mockChatSessionManager) Broadcast(ctx context.Context, msg oscar.XMessage) {
	_m.Called(ctx, msg)
}

// mockChatSessionManager_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type mockChatSessionManager_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - ctx context.Context
//   - msg oscar.XMessage
func (_e *mockChatSessionManager_Expecter) Broadcast(ctx interface{}, msg interface{}) *mockChatSessionManager_Broadcast_Call {
	return &mockChatSessionManager_Broadcast_Call{Call: _e.mock.On("Broadcast", ctx, msg)}
}

func (_c *mockChatSessionManager_Broadcast_Call) Run(run func(ctx context.Context, msg oscar.XMessage)) *mockChatSessionManager_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oscar.XMessage))
	})
	return _c
}

func (_c *mockChatSessionManager_Broadcast_Call) Return() *mockChatSessionManager_Broadcast_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockChatSessionManager_Broadcast_Call) RunAndReturn(run func(context.Context, oscar.XMessage)) *mockChatSessionManager_Broadcast_Call {
	_c.Call.Return(run)
	return _c
}

// BroadcastExcept provides a mock function with given fields: ctx, except, msg
func (_m *mockChatSessionManager) BroadcastExcept(ctx context.Context, except *state.Session, msg oscar.XMessage) {
	_m.Called(ctx, except, msg)
}

// mockChatSessionManager_BroadcastExcept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastExcept'
type mockChatSessionManager_BroadcastExcept_Call struct {
	*mock.Call
}

// BroadcastExcept is a helper method to define mock.On call
//   - ctx context.Context
//   - except *state.Session
//   - msg oscar.XMessage
func (_e *mockChatSessionManager_Expecter) BroadcastExcept(ctx interface{}, except interface{}, msg interface{}) *mockChatSessionManager_BroadcastExcept_Call {
	return &mockChatSessionManager_BroadcastExcept_Call{Call: _e.mock.On("BroadcastExcept", ctx, except, msg)}
}

func (_c *mockChatSessionManager_BroadcastExcept_Call) Run(run func(ctx context.Context, except *state.Session, msg oscar.XMessage)) *mockChatSessionManager_BroadcastExcept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*state.Session), args[2].(oscar.XMessage))
	})
	return _c
}

func (_c *mockChatSessionManager_BroadcastExcept_Call) Return() *mockChatSessionManager_BroadcastExcept_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockChatSessionManager_BroadcastExcept_Call) RunAndReturn(run func(context.Context, *state.Session, oscar.XMessage)) *mockChatSessionManager_BroadcastExcept_Call {
	_c.Call.Return(run)
	return _c
}

// BroadcastToScreenNames provides a mock function with given fields: ctx, screenNames, msg
func (_m *mockChatSessionManager) BroadcastToScreenNames(ctx context.Context, screenNames []string, msg oscar.XMessage) {
	_m.Called(ctx, screenNames, msg)
}

// mockChatSessionManager_BroadcastToScreenNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastToScreenNames'
type mockChatSessionManager_BroadcastToScreenNames_Call struct {
	*mock.Call
}

// BroadcastToScreenNames is a helper method to define mock.On call
//   - ctx context.Context
//   - screenNames []string
//   - msg oscar.XMessage
func (_e *mockChatSessionManager_Expecter) BroadcastToScreenNames(ctx interface{}, screenNames interface{}, msg interface{}) *mockChatSessionManager_BroadcastToScreenNames_Call {
	return &mockChatSessionManager_BroadcastToScreenNames_Call{Call: _e.mock.On("BroadcastToScreenNames", ctx, screenNames, msg)}
}

func (_c *mockChatSessionManager_BroadcastToScreenNames_Call) Run(run func(ctx context.Context, screenNames []string, msg oscar.XMessage)) *mockChatSessionManager_BroadcastToScreenNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(oscar.XMessage))
	})
	return _c
}

func (_c *mockChatSessionManager_BroadcastToScreenNames_Call) Return() *mockChatSessionManager_BroadcastToScreenNames_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockChatSessionManager_BroadcastToScreenNames_Call) RunAndReturn(run func(context.Context, []string, oscar.XMessage)) *mockChatSessionManager_BroadcastToScreenNames_Call {
	_c.Call.Return(run)
	return _c
}

// Empty provides a mock function with given fields:
func (_m *mockChatSessionManager) Empty() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// mockChatSessionManager_Empty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Empty'
type mockChatSessionManager_Empty_Call struct {
	*mock.Call
}

// Empty is a helper method to define mock.On call
func (_e *mockChatSessionManager_Expecter) Empty() *mockChatSessionManager_Empty_Call {
	return &mockChatSessionManager_Empty_Call{Call: _e.mock.On("Empty")}
}

func (_c *mockChatSessionManager_Empty_Call) Run(run func()) *mockChatSessionManager_Empty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockChatSessionManager_Empty_Call) Return(_a0 bool) *mockChatSessionManager_Empty_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockChatSessionManager_Empty_Call) RunAndReturn(run func() bool) *mockChatSessionManager_Empty_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionWithSN provides a mock function with given fields: sessID, screenName
func (_m *mockChatSessionManager) NewSessionWithSN(sessID string, screenName string) *state.Session {
	ret := _m.Called(sessID, screenName)

	var r0 *state.Session
	if rf, ok := ret.Get(0).(func(string, string) *state.Session); ok {
		r0 = rf(sessID, screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.Session)
		}
	}

	return r0
}

// mockChatSessionManager_NewSessionWithSN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewSessionWithSN'
type mockChatSessionManager_NewSessionWithSN_Call struct {
	*mock.Call
}

// NewSessionWithSN is a helper method to define mock.On call
//   - sessID string
//   - screenName string
func (_e *mockChatSessionManager_Expecter) NewSessionWithSN(sessID interface{}, screenName interface{}) *mockChatSessionManager_NewSessionWithSN_Call {
	return &mockChatSessionManager_NewSessionWithSN_Call{Call: _e.mock.On("NewSessionWithSN", sessID, screenName)}
}

func (_c *mockChatSessionManager_NewSessionWithSN_Call) Run(run func(sessID string, screenName string)) *mockChatSessionManager_NewSessionWithSN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *mockChatSessionManager_NewSessionWithSN_Call) Return(_a0 *state.Session) *mockChatSessionManager_NewSessionWithSN_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockChatSessionManager_NewSessionWithSN_Call) RunAndReturn(run func(string, string) *state.Session) *mockChatSessionManager_NewSessionWithSN_Call {
	_c.Call.Return(run)
	return _c
}

// Participants provides a mock function with given fields:
func (_m *mockChatSessionManager) Participants() []*state.Session {
	ret := _m.Called()

	var r0 []*state.Session
	if rf, ok := ret.Get(0).(func() []*state.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*state.Session)
		}
	}

	return r0
}

// mockChatSessionManager_Participants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Participants'
type mockChatSessionManager_Participants_Call struct {
	*mock.Call
}

// Participants is a helper method to define mock.On call
func (_e *mockChatSessionManager_Expecter) Participants() *mockChatSessionManager_Participants_Call {
	return &mockChatSessionManager_Participants_Call{Call: _e.mock.On("Participants")}
}

func (_c *mockChatSessionManager_Participants_Call) Run(run func()) *mockChatSessionManager_Participants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockChatSessionManager_Participants_Call) Return(_a0 []*state.Session) *mockChatSessionManager_Participants_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockChatSessionManager_Participants_Call) RunAndReturn(run func() []*state.Session) *mockChatSessionManager_Participants_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: sess
func (_m *mockChatSessionManager) Remove(sess *state.Session) {
	_m.Called(sess)
}

// mockChatSessionManager_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type mockChatSessionManager_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - sess *state.Session
func (_e *mockChatSessionManager_Expecter) Remove(sess interface{}) *mockChatSessionManager_Remove_Call {
	return &mockChatSessionManager_Remove_Call{Call: _e.mock.On("Remove", sess)}
}

func (_c *mockChatSessionManager_Remove_Call) Run(run func(sess *state.Session)) *mockChatSessionManager_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*state.Session))
	})
	return _c
}

func (_c *mockChatSessionManager_Remove_Call) Return() *mockChatSessionManager_Remove_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockChatSessionManager_Remove_Call) RunAndReturn(run func(*state.Session)) *mockChatSessionManager_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function with given fields: ID
func (_m *mockChatSessionManager) Retrieve(ID string) (*state.Session, bool) {
	ret := _m.Called(ID)

	var r0 *state.Session
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*state.Session, bool)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(string) *state.Session); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// mockChatSessionManager_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type mockChatSessionManager_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ID string
func (_e *mockChatSessionManager_Expecter) Retrieve(ID interface{}) *mockChatSessionManager_Retrieve_Call {
	return &mockChatSessionManager_Retrieve_Call{Call: _e.mock.On("Retrieve", ID)}
}

func (_c *mockChatSessionManager_Retrieve_Call) Run(run func(ID string)) *mockChatSessionManager_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockChatSessionManager_Retrieve_Call) Return(_a0 *state.Session, _a1 bool) *mockChatSessionManager_Retrieve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockChatSessionManager_Retrieve_Call) RunAndReturn(run func(string) (*state.Session, bool)) *mockChatSessionManager_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveByScreenName provides a mock function with given fields: screenName
func (_m *mockChatSessionManager) RetrieveByScreenName(screenName string) *state.Session {
	ret := _m.Called(screenName)

	var r0 *state.Session
	if rf, ok := ret.Get(0).(func(string) *state.Session); ok {
		r0 = rf(screenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.Session)
		}
	}

	return r0
}

// mockChatSessionManager_RetrieveByScreenName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveByScreenName'
type mockChatSessionManager_RetrieveByScreenName_Call struct {
	*mock.Call
}

// RetrieveByScreenName is a helper method to define mock.On call
//   - screenName string
func (_e *mockChatSessionManager_Expecter) RetrieveByScreenName(screenName interface{}) *mockChatSessionManager_RetrieveByScreenName_Call {
	return &mockChatSessionManager_RetrieveByScreenName_Call{Call: _e.mock.On("RetrieveByScreenName", screenName)}
}

func (_c *mockChatSessionManager_RetrieveByScreenName_Call) Run(run func(screenName string)) *mockChatSessionManager_RetrieveByScreenName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockChatSessionManager_RetrieveByScreenName_Call) Return(_a0 *state.Session) *mockChatSessionManager_RetrieveByScreenName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockChatSessionManager_RetrieveByScreenName_Call) RunAndReturn(run func(string) *state.Session) *mockChatSessionManager_RetrieveByScreenName_Call {
	_c.Call.Return(run)
	return _c
}

// SendToScreenName provides a mock function with given fields: ctx, screenName, msg
func (_m *mockChatSessionManager) SendToScreenName(ctx context.Context, screenName string, msg oscar.XMessage) {
	_m.Called(ctx, screenName, msg)
}

// mockChatSessionManager_SendToScreenName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendToScreenName'
type mockChatSessionManager_SendToScreenName_Call struct {
	*mock.Call
}

// SendToScreenName is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName string
//   - msg oscar.XMessage
func (_e *mockChatSessionManager_Expecter) SendToScreenName(ctx interface{}, screenName interface{}, msg interface{}) *mockChatSessionManager_SendToScreenName_Call {
	return &mockChatSessionManager_SendToScreenName_Call{Call: _e.mock.On("SendToScreenName", ctx, screenName, msg)}
}

func (_c *mockChatSessionManager_SendToScreenName_Call) Run(run func(ctx context.Context, screenName string, msg oscar.XMessage)) *mockChatSessionManager_SendToScreenName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(oscar.XMessage))
	})
	return _c
}

func (_c *mockChatSessionManager_SendToScreenName_Call) Return() *mockChatSessionManager_SendToScreenName_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockChatSessionManager_SendToScreenName_Call) RunAndReturn(run func(context.Context, string, oscar.XMessage)) *mockChatSessionManager_SendToScreenName_Call {
	_c.Call.Return(run)
	return _c
}

// newMockChatSessionManager creates a new instance of mockChatSessionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockChatSessionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockChatSessionManager {
	mock := &mockChatSessionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
