// Code generated by mockery v2.45.0. DO NOT EDIT.

package http

import (
	state "github.com/mk6i/retro-aim-server/state"
	mock "github.com/stretchr/testify/mock"
)

// mockDirectoryManager is an autogenerated mock type for the DirectoryManager type
type mockDirectoryManager struct {
	mock.Mock
}

type mockDirectoryManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDirectoryManager) EXPECT() *mockDirectoryManager_Expecter {
	return &mockDirectoryManager_Expecter{mock: &_m.Mock}
}

// Categories provides a mock function with given fields:
func (_m *mockDirectoryManager) Categories() ([]state.Category, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Categories")
	}

	var r0 []state.Category
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]state.Category, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []state.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]state.Category)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDirectoryManager_Categories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Categories'
type mockDirectoryManager_Categories_Call struct {
	*mock.Call
}

// Categories is a helper method to define mock.On call
func (_e *mockDirectoryManager_Expecter) Categories() *mockDirectoryManager_Categories_Call {
	return &mockDirectoryManager_Categories_Call{Call: _e.mock.On("Categories")}
}

func (_c *mockDirectoryManager_Categories_Call) Run(run func()) *mockDirectoryManager_Categories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDirectoryManager_Categories_Call) Return(_a0 []state.Category, _a1 error) *mockDirectoryManager_Categories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDirectoryManager_Categories_Call) RunAndReturn(run func() ([]state.Category, error)) *mockDirectoryManager_Categories_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCategory provides a mock function with given fields: name
func (_m *mockDirectoryManager) CreateCategory(name string) (state.Category, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 state.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (state.Category, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) state.Category); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(state.Category)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDirectoryManager_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type mockDirectoryManager_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - name string
func (_e *mockDirectoryManager_Expecter) CreateCategory(name interface{}) *mockDirectoryManager_CreateCategory_Call {
	return &mockDirectoryManager_CreateCategory_Call{Call: _e.mock.On("CreateCategory", name)}
}

func (_c *mockDirectoryManager_CreateCategory_Call) Run(run func(name string)) *mockDirectoryManager_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockDirectoryManager_CreateCategory_Call) Return(_a0 state.Category, _a1 error) *mockDirectoryManager_CreateCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDirectoryManager_CreateCategory_Call) RunAndReturn(run func(string) (state.Category, error)) *mockDirectoryManager_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKeyword provides a mock function with given fields: name, categoryID
func (_m *mockDirectoryManager) CreateKeyword(name string, categoryID uint8) (state.Keyword, error) {
	ret := _m.Called(name, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for CreateKeyword")
	}

	var r0 state.Keyword
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uint8) (state.Keyword, error)); ok {
		return rf(name, categoryID)
	}
	if rf, ok := ret.Get(0).(func(string, uint8) state.Keyword); ok {
		r0 = rf(name, categoryID)
	} else {
		r0 = ret.Get(0).(state.Keyword)
	}

	if rf, ok := ret.Get(1).(func(string, uint8) error); ok {
		r1 = rf(name, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDirectoryManager_CreateKeyword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeyword'
type mockDirectoryManager_CreateKeyword_Call struct {
	*mock.Call
}

// CreateKeyword is a helper method to define mock.On call
//   - name string
//   - categoryID uint8
func (_e *mockDirectoryManager_Expecter) CreateKeyword(name interface{}, categoryID interface{}) *mockDirectoryManager_CreateKeyword_Call {
	return &mockDirectoryManager_CreateKeyword_Call{Call: _e.mock.On("CreateKeyword", name, categoryID)}
}

func (_c *mockDirectoryManager_CreateKeyword_Call) Run(run func(name string, categoryID uint8)) *mockDirectoryManager_CreateKeyword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(uint8))
	})
	return _c
}

func (_c *mockDirectoryManager_CreateKeyword_Call) Return(_a0 state.Keyword, _a1 error) *mockDirectoryManager_CreateKeyword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDirectoryManager_CreateKeyword_Call) RunAndReturn(run func(string, uint8) (state.Keyword, error)) *mockDirectoryManager_CreateKeyword_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCategory provides a mock function with given fields: categoryID
func (_m *mockDirectoryManager) DeleteCategory(categoryID uint8) error {
	ret := _m.Called(categoryID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint8) error); ok {
		r0 = rf(categoryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDirectoryManager_DeleteCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCategory'
type mockDirectoryManager_DeleteCategory_Call struct {
	*mock.Call
}

// DeleteCategory is a helper method to define mock.On call
//   - categoryID uint8
func (_e *mockDirectoryManager_Expecter) DeleteCategory(categoryID interface{}) *mockDirectoryManager_DeleteCategory_Call {
	return &mockDirectoryManager_DeleteCategory_Call{Call: _e.mock.On("DeleteCategory", categoryID)}
}

func (_c *mockDirectoryManager_DeleteCategory_Call) Run(run func(categoryID uint8)) *mockDirectoryManager_DeleteCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint8))
	})
	return _c
}

func (_c *mockDirectoryManager_DeleteCategory_Call) Return(_a0 error) *mockDirectoryManager_DeleteCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDirectoryManager_DeleteCategory_Call) RunAndReturn(run func(uint8) error) *mockDirectoryManager_DeleteCategory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKeyword provides a mock function with given fields: id
func (_m *mockDirectoryManager) DeleteKeyword(id uint8) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKeyword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint8) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDirectoryManager_DeleteKeyword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKeyword'
type mockDirectoryManager_DeleteKeyword_Call struct {
	*mock.Call
}

// DeleteKeyword is a helper method to define mock.On call
//   - id uint8
func (_e *mockDirectoryManager_Expecter) DeleteKeyword(id interface{}) *mockDirectoryManager_DeleteKeyword_Call {
	return &mockDirectoryManager_DeleteKeyword_Call{Call: _e.mock.On("DeleteKeyword", id)}
}

func (_c *mockDirectoryManager_DeleteKeyword_Call) Run(run func(id uint8)) *mockDirectoryManager_DeleteKeyword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint8))
	})
	return _c
}

func (_c *mockDirectoryManager_DeleteKeyword_Call) Return(_a0 error) *mockDirectoryManager_DeleteKeyword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDirectoryManager_DeleteKeyword_Call) RunAndReturn(run func(uint8) error) *mockDirectoryManager_DeleteKeyword_Call {
	_c.Call.Return(run)
	return _c
}

// KeywordsByCategory provides a mock function with given fields: categoryID
func (_m *mockDirectoryManager) KeywordsByCategory(categoryID uint8) ([]state.Keyword, error) {
	ret := _m.Called(categoryID)

	if len(ret) == 0 {
		panic("no return value specified for KeywordsByCategory")
	}

	var r0 []state.Keyword
	var r1 error
	if rf, ok := ret.Get(0).(func(uint8) ([]state.Keyword, error)); ok {
		return rf(categoryID)
	}
	if rf, ok := ret.Get(0).(func(uint8) []state.Keyword); ok {
		r0 = rf(categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]state.Keyword)
		}
	}

	if rf, ok := ret.Get(1).(func(uint8) error); ok {
		r1 = rf(categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDirectoryManager_KeywordsByCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeywordsByCategory'
type mockDirectoryManager_KeywordsByCategory_Call struct {
	*mock.Call
}

// KeywordsByCategory is a helper method to define mock.On call
//   - categoryID uint8
func (_e *mockDirectoryManager_Expecter) KeywordsByCategory(categoryID interface{}) *mockDirectoryManager_KeywordsByCategory_Call {
	return &mockDirectoryManager_KeywordsByCategory_Call{Call: _e.mock.On("KeywordsByCategory", categoryID)}
}

func (_c *mockDirectoryManager_KeywordsByCategory_Call) Run(run func(categoryID uint8)) *mockDirectoryManager_KeywordsByCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint8))
	})
	return _c
}

func (_c *mockDirectoryManager_KeywordsByCategory_Call) Return(_a0 []state.Keyword, _a1 error) *mockDirectoryManager_KeywordsByCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDirectoryManager_KeywordsByCategory_Call) RunAndReturn(run func(uint8) ([]state.Keyword, error)) *mockDirectoryManager_KeywordsByCategory_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDirectoryManager creates a new instance of mockDirectoryManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDirectoryManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDirectoryManager {
	mock := &mockDirectoryManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
